"""add_knowledge_books

Revision ID: 74f9b83d31d7
Revises: dbbb683b3006
Create Date: 2026-09-15 06:05:43.341391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f9b83d31d7'
down_revision: Union[str, Sequence[str], None] = 'dbbb683b3006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_books',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('target_length', sa.String(length=50), nullable=True),
    sa.Column('target_chapters', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('markdown_path', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('outline_json', sa.JSON(), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['async_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_books_status'), 'knowledge_books', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_books_user_id'), 'knowledge_books', ['user_id'], unique=False)
    op.create_table('knowledge_chapters',
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('outline_json', sa.JSON(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['knowledge_books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chapters_book_id'), 'knowledge_chapters', ['book_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chapters_status'), 'knowledge_chapters', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chapters_status'), table_name='knowledge_chapters')
    op.drop_index(op.f('ix_knowledge_chapters_book_id'), table_name='knowledge_chapters')
    op.drop_table('knowledge_chapters')
    op.drop_index(op.f('ix_knowledge_books_user_id'), table_name='knowledge_books')
    op.drop_index(op.f('ix_knowledge_books_status'), table_name='knowledge_books')
    op.drop_table('knowledge_books')
    # ### end Alembic commands ###
