"""implement_target_architecture

Revision ID: 8461ad4a6220
Revises: 9484cc1562a9
Create Date: 2026-09-14 20:25:22.161296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8461ad4a6220'
down_revision: Union[str, Sequence[str], None] = '9484cc1562a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_cache_cache_key'), 'ai_cache', ['cache_key'], unique=True)
    op.create_table('ai_requests',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_requests_status'), 'ai_requests', ['status'], unique=False)
    op.create_index(op.f('ix_ai_requests_user_id'), 'ai_requests', ['user_id'], unique=False)
    op.create_table('ai_usage',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('billing_period', sa.String(length=50), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_billing_period'), 'ai_usage', ['billing_period'], unique=False)
    op.create_index(op.f('ix_ai_usage_user_id'), 'ai_usage', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_status'), 'courses', ['status'], unique=False)
    op.create_index(op.f('ix_courses_user_id'), 'courses', ['user_id'], unique=False)
    op.create_table('assignments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_due_date'), 'assignments', ['due_date'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_index(op.f('ix_assignments_subject_id'), 'assignments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_assignments_user_id'), 'assignments', ['user_id'], unique=False)
    op.create_table('chapters',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_course_id'), 'chapters', ['course_id'], unique=False)
    op.create_table('conversation_summaries',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('messages_summarized', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_summaries_conversation_id'), 'conversation_summaries', ['conversation_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    
    # Prepare pgvector conditionally without breaking SQLite operation
    conn = op.get_bind()
    if conn.dialect.name == 'postgresql':
        op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
        op.execute("ALTER TABLE document_chunks ALTER COLUMN embedding TYPE vector(768) USING embedding::text::vector;")
    op.create_table('knowledge_nodes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('concept_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_nodes_subject_id'), 'knowledge_nodes', ['subject_id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_user_id'), 'knowledge_nodes', ['user_id'], unique=False)
    op.create_table('timetable_events',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_events_start_time'), 'timetable_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_timetable_events_subject_id'), 'timetable_events', ['subject_id'], unique=False)
    op.create_index(op.f('ix_timetable_events_user_id'), 'timetable_events', ['user_id'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('source_node_id', sa.String(length=36), nullable=False),
    sa.Column('target_node_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_edges_source_node_id'), 'knowledge_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_target_node_id'), 'knowledge_edges', ['target_node_id'], unique=False)
    op.create_table('sections',
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_chapter_id'), 'sections', ['chapter_id'], unique=False)
    op.alter_column('admin_audit_logs', 'details_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_admin_audit_logs_action_type'), 'admin_audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_admin_id'), 'admin_audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_target_user_id'), 'admin_audit_logs', ['target_user_id'], unique=False)
    op.alter_column('notes', 'tiptap_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_resource_shares_group_id'), 'resource_shares', ['group_id'], unique=False)
    op.create_index(op.f('ix_resource_shares_owner_id'), 'resource_shares', ['owner_id'], unique=False)
    op.create_index(op.f('ix_resource_shares_resource_id'), 'resource_shares', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_shares_shared_with_id'), 'resource_shares', ['shared_with_id'], unique=False)
    op.alter_column('study_blocks', 'subject_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_foreign_key(None, 'study_blocks', 'notes', ['note_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('user_connections_blocked_by_id_fkey'), 'user_connections', type_='foreignkey')
    op.drop_column('user_connections', 'blocked_by_id')
    op.drop_column('users', 'raw_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('raw_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_connections', sa.Column('blocked_by_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_connections_blocked_by_id_fkey'), 'user_connections', 'users', ['blocked_by_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'study_blocks', type_='foreignkey')
    op.alter_column('study_blocks', 'subject_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index(op.f('ix_resource_shares_shared_with_id'), table_name='resource_shares')
    op.drop_index(op.f('ix_resource_shares_resource_id'), table_name='resource_shares')
    op.drop_index(op.f('ix_resource_shares_owner_id'), table_name='resource_shares')
    op.drop_index(op.f('ix_resource_shares_group_id'), table_name='resource_shares')
    op.alter_column('notes', 'tiptap_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_audit_logs_target_user_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action_type'), table_name='admin_audit_logs')
    op.alter_column('admin_audit_logs', 'details_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_sections_chapter_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_knowledge_edges_target_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_source_node_id'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index(op.f('ix_timetable_events_user_id'), table_name='timetable_events')
    op.drop_index(op.f('ix_timetable_events_subject_id'), table_name='timetable_events')
    op.drop_index(op.f('ix_timetable_events_start_time'), table_name='timetable_events')
    op.drop_table('timetable_events')
    op.drop_index(op.f('ix_knowledge_nodes_user_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_subject_id'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_conversation_summaries_conversation_id'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    op.drop_index(op.f('ix_chapters_course_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_assignments_user_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_subject_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_due_date'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_courses_user_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_status'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_ai_usage_user_id'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_billing_period'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_ai_requests_user_id'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_status'), table_name='ai_requests')
    op.drop_table('ai_requests')
    op.drop_index(op.f('ix_ai_cache_cache_key'), table_name='ai_cache')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
