"""initial_snapshot

Revision ID: 9484cc1562a9
Revises: 
Create Date: 2026-09-14 20:23:18.380918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9484cc1562a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_audit_logs', 'details_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_admin_audit_logs_action_type'), 'admin_audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_admin_id'), 'admin_audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_target_user_id'), 'admin_audit_logs', ['target_user_id'], unique=False)
    op.alter_column('notes', 'tiptap_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_resource_shares_group_id'), 'resource_shares', ['group_id'], unique=False)
    op.create_index(op.f('ix_resource_shares_owner_id'), 'resource_shares', ['owner_id'], unique=False)
    op.create_index(op.f('ix_resource_shares_resource_id'), 'resource_shares', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_shares_shared_with_id'), 'resource_shares', ['shared_with_id'], unique=False)
    op.alter_column('study_blocks', 'subject_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_foreign_key(None, 'study_blocks', 'notes', ['note_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('user_connections_blocked_by_id_fkey'), 'user_connections', type_='foreignkey')
    op.drop_column('user_connections', 'blocked_by_id')
    op.drop_column('users', 'raw_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('raw_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_connections', sa.Column('blocked_by_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_connections_blocked_by_id_fkey'), 'user_connections', 'users', ['blocked_by_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'study_blocks', type_='foreignkey')
    op.alter_column('study_blocks', 'subject_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index(op.f('ix_resource_shares_shared_with_id'), table_name='resource_shares')
    op.drop_index(op.f('ix_resource_shares_resource_id'), table_name='resource_shares')
    op.drop_index(op.f('ix_resource_shares_owner_id'), table_name='resource_shares')
    op.drop_index(op.f('ix_resource_shares_group_id'), table_name='resource_shares')
    op.alter_column('notes', 'tiptap_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_audit_logs_target_user_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action_type'), table_name='admin_audit_logs')
    op.alter_column('admin_audit_logs', 'details_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
