"""document_rag_fields

Revision ID: e95112641cff
Revises: f6222fff3bfd
Create Date: 2026-09-15 05:35:23.559522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95112641cff'
down_revision: Union[str, Sequence[str], None] = 'f6222fff3bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('subject_id', sa.String(length=36), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(length=50), nullable=False, server_default='pending'))
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_subject_id'), 'documents', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_subject_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'subject_id')
    op.drop_column('document_chunks', 'page_number')
    # ### end Alembic commands ###
