"""ai_semantic_cache

Revision ID: f6222fff3bfd
Revises: 8461ad4a6220
Create Date: 2026-09-15 05:30:03.109131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6222fff3bfd'
down_revision: Union[str, Sequence[str], None] = '8461ad4a6220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_cache', sa.Column('prompt_version', sa.String(length=50), nullable=False))
    op.add_column('ai_cache', sa.Column('task_category', sa.String(length=50), nullable=False))
    op.add_column('ai_cache', sa.Column('normalized_prompt', sa.Text(), nullable=True))
    op.add_column('ai_cache', sa.Column('embedding', sa.JSON(), nullable=True))
    op.add_column('ai_cache', sa.Column('is_personalized', sa.Boolean(), nullable=False))
    op.add_column('ai_cache', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_ai_cache_user_id'), 'ai_cache', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ai_cache', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # Postgres specific pgvector logic for semantic cache
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.execute('ALTER TABLE ai_cache ALTER COLUMN embedding TYPE VECTOR(768) USING embedding::text::vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.execute('ALTER TABLE ai_cache ALTER COLUMN embedding TYPE JSON USING embedding::text::json')

    op.drop_constraint(None, 'ai_cache', type_='foreignkey')
    op.drop_index(op.f('ix_ai_cache_user_id'), table_name='ai_cache')
    op.drop_column('ai_cache', 'user_id')
    op.drop_column('ai_cache', 'is_personalized')
    op.drop_column('ai_cache', 'embedding')
    op.drop_column('ai_cache', 'normalized_prompt')
    op.drop_column('ai_cache', 'task_category')
    op.drop_column('ai_cache', 'prompt_version')
    # ### end Alembic commands ###
